# somewhere рядом с install_command (или отдельный файл engine/frozen.py)

from pathlib import Path
from typing import Iterable
from autumn.cli.environment.engine.models import LockFile, LockedRequirement
from autumn.cli.environment.engine.paths import AutumnPaths

class FrozenLockError(RuntimeError):
    pass

def _req_line_with_hashes(name: str, version: str, hashes: Iterable[str]) -> str:
    # pip требует формат sha256:...
    h = [f"    --hash=sha256:{x}" for x in hashes]
    return "\n".join([f"{name}=={version}"] + h)

def build_frozen_requirements_file(
    lock: LockFile,
    paths: AutumnPaths,
    env_name: str,
    groups: list[str],
) -> Path:
    req_dir = paths.cache_directory / "frozen"
    req_dir.mkdir(parents=True, exist_ok=True)
    req_path = req_dir / f"{env_name}.requirements.txt"

    lines: list[str] = []
    lines.append("# Generated by autumn (frozen)")
    lines.append("")  # визуально

    for group in groups:
        if group not in lock.groups:
            raise FrozenLockError(f"Group '{group}' missing in lock")

        lines.append(f"# group: {group}")

        for item in lock.groups[group].resolved:
            lines.extend(_locked_item_to_lines(item))

        lines.append("")

    content = "\n".join(lines).strip() + "\n"
    req_path.write_text(content, encoding="utf-8")
    return req_path

def _locked_item_to_lines(item: LockedRequirement) -> list[str]:
    # запретим всё недетерминированное
    if item.editable or item.source.type in ("git", "path"):
        raise FrozenLockError(
            f"Non-deterministic dependency in lock: {item.name} ({item.source.type}, editable={item.editable})"
        )

    if item.source.type in ("pypi", "url"):
        if not item.artifacts:
            raise FrozenLockError(f"Missing artifacts for locked dependency: {item.name} ({item.source.type})")

        hashes = [a.sha256 for a in item.artifacts if a.sha256]
        if not hashes:
            raise FrozenLockError(f"Missing sha256 hashes for: {item.name}")

        # В frozen всегда пиним версию. (У тебя version может быть 'direct' — тогда это тоже плохо)
        if not item.version or item.version in ("direct", "editable"):
            raise FrozenLockError(f"Non-pinned version in lock for: {item.name} (version={item.version})")

        return [_req_line_with_hashes(item.name, item.version, hashes), ""]

    # unknown -> тоже запрет
    raise FrozenLockError(f"Unsupported locked dependency source: {item.name} ({item.source.type})")
