# engine/frozen.py

from __future__ import annotations

from pathlib import Path
from typing import Dict, Iterable, Set, Tuple, List

from autumn.cli.environment.engine.models import LockFile, LockedRequirement
from autumn.cli.environment.engine.paths import AutumnPaths

import hashlib
import shutil


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


class FrozenLockError(RuntimeError):
    pass


def _req_line_with_hashes(name: str, version: str, hashes: Iterable[str]) -> str:
    # pip требует формат: --hash=sha256:...
    h = [f"    --hash=sha256:{x}" for x in hashes]
    return "\n".join([f"{name}=={version}"] + h)


def build_frozen_requirements_file(
    lock: LockFile,
    paths: AutumnPaths,
    env_name: str,
    groups: list[str],
) -> tuple[Path, Path]:
    req_dir = paths.cache_directory / "frozen"
    req_dir.mkdir(parents=True, exist_ok=True)
    req_path = req_dir / f"{env_name}.requirements.txt"

    pool_dir = paths.frozen_artifacts_directory(env_name)
    if pool_dir.exists():
        shutil.rmtree(pool_dir)
    pool_dir.mkdir(parents=True, exist_ok=True)

    # name -> (version, hashes)
    acc: Dict[str, Tuple[str, Set[str]]] = {}

    for group in groups:
        if group not in lock.groups:
            raise FrozenLockError(f"Group '{group}' missing in lock")

        for item in lock.groups[group].resolved:
            _stage_artifacts_to_pool(item, paths, pool_dir)
            _accumulate_locked_item(acc, item, group=group)

    lines: list[str] = []
    lines.append("# Generated by autumn (frozen)")
    lines.append("")
    lines.append(f"# environment: {env_name}")
    lines.append(f"# groups: {', '.join(groups)}")
    lines.append("")

    for name in sorted(acc.keys()):
        version, hashes = acc[name]
        lines.append(_req_line_with_hashes(name, version, sorted(hashes)))
        lines.append("")

    content = "\n".join(lines).strip() + "\n"
    req_path.write_text(content, encoding="utf-8")

    return req_path, pool_dir


def _accumulate_locked_item(
    acc: Dict[str, Tuple[str, Set[str]]],
    item: LockedRequirement,
    *,
    group: str,
) -> None:
    # запретим всё недетерминированное
    if item.editable or item.source.type in ("git", "path"):
        raise FrozenLockError(
            f"Non-deterministic dependency in lock: {item.name} "
            f"({item.source.type}, editable={item.editable}) in group '{group}'"
        )

    if item.source.type not in ("pypi", "url"):
        raise FrozenLockError(
            f"Unsupported locked dependency source: {item.name} "
            f"({item.source.type}) in group '{group}'"
        )

    if not item.artifacts:
        raise FrozenLockError(
            f"Missing artifacts for locked dependency: {item.name} "
            f"({item.source.type}) in group '{group}'"
        )

    hashes = {a.sha256 for a in item.artifacts if a.sha256}
    if not hashes:
        raise FrozenLockError(f"Missing sha256 hashes for: {item.name} in group '{group}'")

    # frozen требует pinned
    if not item.version or item.version in ("direct", "editable"):
        raise FrozenLockError(
            f"Non-pinned version in lock for: {item.name} "
            f"(version={item.version}) in group '{group}'"
        )

    name = item.name

    if name not in acc:
        acc[name] = (item.version, set(hashes))
        return

    existing_version, existing_hashes = acc[name]
    if existing_version != item.version:
        raise FrozenLockError(
            f"Version conflict for '{name}': group '{group}' has {item.version}, "
            f"but already locked as {existing_version}"
        )

    existing_hashes.update(hashes)


def _stage_artifacts_to_pool(item: LockedRequirement, paths: AutumnPaths, pool_dir: Path) -> None:
    if item.source.type not in ("pypi", "url"):
        return

    for a in item.artifacts:
        src = paths.project_root / a.local_path
        if not src.exists():
            raise FrozenLockError(f"Artifact missing on disk for {item.name}: {a.local_path}")

        dst = pool_dir / a.filename

        # если уже есть — ок, но проверим sha256 (коллизии имён ловим)
        if dst.exists():
            current_sha = sha256_file(dst)
            if current_sha != a.sha256:
                raise FrozenLockError(
                    f"Artifact filename collision in pool: {dst.name} "
                    f"(expected sha256={a.sha256}, got={current_sha})"
                )
            continue

        # стараемся хардлинк, если не получится — копируем
        try:
            dst.hardlink_to(src)
        except Exception:
            shutil.copy2(src, dst)
