class AutumnConfigAliasError(TypeError):
    ...

class AutumnConfigError(RuntimeError):
    ...

class AutumnConfigValueMissing(AutumnConfigError):
    ...
    
class AutumnConfigCastError(AutumnConfigError):
    ...

class AutumnConfigSourceError(AutumnConfigError):
    ...